#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
币安API错误码映射

此模块定义了与币安API兼容的错误码
"""

# 服务器或网络错误 (-1xxx)
# 币安常用 -1000 UNKNOWN, -1001 DISCONNECTED, -1002 UNAUTHORIZED, -1003 TOO_MANY_REQUESTS
# -1014 INVALID_MESSAGE, -1015 TIMEOUT, -1016 UNKNOWN_ORDER_COMPOSITION
# -1021 INVALID_TIMESTAMP, -1022 INVALID_SIGNATURE (我们用 INVALID_PARAM 代替了一部分)
UNKNOWN_ERROR = -1000  # 未知错误 (币安常用)
DISCONNECTED = -1001  # 与服务器断开连接
UNAUTHORIZED = -1002  # 未授权 (例如API Key无效或缺失)
TOO_MANY_REQUESTS = -1003  # 请求过多 (通用)
# SERVER_BUSY = -1004 # QTE自定义，币安似乎没有这个特定码
TIMEOUT = -1015  # 超时 (币安常用)
# UNKNOWN_ORDER_COMPOSITION = -1006 # QTE自定义
# UNEXPECTED_RESP = -1007 # QTE自定义, 对应币安的 -1000 或 HTTP 500
INVALID_MESSAGE = -1014 # 消息无效 (例如参数无法解析)
INVALID_TIMESTAMP = -1021  # 无效的时间戳 (币安常用)
INVALID_SIGNATURE = -1022 # 无效的签名 (币安常用) - 注意：之前 INVALID_PARAM 用了这个值

# QTE 自定义或需要重新映射的 -1xxx
SERVER_BUSY = -1901  # 服务器繁忙 (QTE自定义，避开币安-10xx)
INTERNAL_SERVER_ERROR = -1902 # 服务器内部错误 (QTE自定义)


# HTTP 状态码映射 (非币安code，但常用于 HTTP 层面)
# HTTP_BAD_REQUEST = 400
# HTTP_UNAUTHORIZED = 401
# HTTP_FORBIDDEN = 403
# HTTP_NOT_FOUND = 404
# HTTP_TOO_MANY_REQUESTS = 429
# HTTP_INTERNAL_SERVER_ERROR = 500


# 请求参数错误 (-11xx) - 币安常用此范围表示参数问题
MANDATORY_PARAM_EMPTY_OR_MALFORMED = -1102 # 参数为空或格式错误
ILLEGAL_CHARS = -1100 # 参数中包含非法字符
INVALID_PARAM_VALUE = -1101 # 参数值无效 (通用，比-1102更具体指值本身)
UNKNOWN_PARAM = -1103 # 未知参数
INVALID_ORDER_ID_PARAM = -1104 # orderId 参数无效 (格式或值)
INVALID_SYMBOL_PARAM = -1105 # symbol 参数无效 (格式或值，区别于 UNKNOWN_SYMBOL)
# -1106: Parameter X was sent when not required (币安已改为 -1128)
PARAM_VALUE_TOO_LONG = -1108 # 参数值太长
INVALID_PRICE_PARAM = -1111 # 价格参数无效
INVALID_QUANTITY_PARAM = -1112 # 数量参数无效
INVALID_PERCENTAGE_PARAM = -1113 # 百分比参数无效
INVALID_TIF_PARAM = -1114 # TimeInForce 参数无效
INVALID_ORDER_TYPE_PARAM = -1115 # 订单类型参数无效
INVALID_ORDER_SIDE_PARAM = -1116 # 订单方向参数无效
INVALID_LIMIT_PARAM = -1120 # Limit 参数无效 (例如超出范围或不在允许值列表)
UNKNOWN_SYMBOL = -1121  # 无效的交易对 (币安常用)
INVALID_LISTEN_KEY = -1125  # 无效的listenKey (币安常用)
MORE_THAN_XX_HOURS = -1127 # 时间范围超过限制 (例如K线查询)
OPTIONAL_PARAMS_BAD_COMBO = -1128 # 可选参数组合无效
INVALID_FILTER_ARGS = -1130 # 过滤器参数无效
INVALID_JSON_FORMAT = -1135 # 参数为无效JSON格式
CANCEL_INVALID_ORDER_STATUS = -1136 # 订单状态不允许取消 (例如已完成或已取消)


# 账户或API密钥错误 (-20xx) - 币安常用此范围
# -2010: NEW_ORDER_REJECTED (通用订单拒绝)
# -2011: CANCEL_REJECTED (通用取消拒绝)
# -2013: Order does not exist (ORDER_NOT_FOUND)
# -2014: API-key format invalid.
# -2015: Invalid API-key, IP, or permissions for action.
NEW_ORDER_REJECTED = -2010  # 新订单被拒绝
CANCEL_REJECTED = -2011  # 取消订单被拒绝
# CANCEL_ALL_FAIL = -2012 # QTE自定义
ORDER_NOT_FOUND = -2013  # 订单不存在 (币安常用)
BAD_API_KEY_FMT = -2014  # API密钥格式无效 (币安常用)
INVALID_API_KEY_OR_PERMISSIONS = -2015  # 无效的API Key, IP,或权限 (币安常用)
UNKNOWN_ACCOUNT = -2016  # 未知账户 (币安常用)
INSUFFICIENT_BALANCE = -2018  # 余额不足 (币安常用，注意和-2017区分，-2017是QTE的)
# SERVER_BUSY_ORDER = -2018 # QTE自定义，币安无此特定码
# INSUFFICIENT_ACCOUNT = -2019 # QTE自定义 (保证金不足)
ORDER_PLACEMENT_NOT_ALLOWED = -2020  # 不允许交易操作 (QTE的ORDER_NOT_ALLOWED)
MARKET_IS_CLOSED = -2021  # 市场已关闭 (币安常用)
PRICE_QTY_EXCEED_HARD_LIMITS = -2022  # 价格*数量超过硬性上限 (币安常用)
# INSUFFICIENT_QUANTITY = -2023 # QTE自定义
TOO_MANY_ORDERS = -2025  # 订单过多 (币安常用，注意和QTE的-2024区分)
ORDER_WOULD_TRIGGER_IMMEDIATELY = -2026  # 订单会立即触发 (币安常用，注意和QTE的-2025区分)
ORDER_ARCHIVED = -2026  # 订单已归档 (币安常用)
# CANCEL_RESTRICTED = -2027 # QTE自定义，币安用-2011 + msg


# 过滤器失败错误 (-4xxx) - 币安常用
PRICE_FILTER_FAILURE = -1013 # 价格过滤器失败 (币安常用) - 注意：这是一个奇怪的-1xxx范围的过滤器错误
LOT_SIZE_FILTER_FAILURE = -2010 # 订单量过滤器失败 (币安常用) - 注意：这个码和NEW_ORDER_REJECTED重复了，需小心
PERCENT_PRICE_FILTER_FAILURE = -2017 # 百分比价格过滤器失败
MIN_NOTIONAL_FILTER_FAILURE = -1013 # 最小名义价值过滤器失败 (币安常用) - 注意：同PRICE_FILTER_FAILURE
ICEBERG_ORDERS_FILTER_FAILURE = -2023 # 冰山订单过滤器失败
MARKET_LOT_SIZE_FILTER_FAILURE = -2024 # 市价单数量过滤器失败
MAX_NUM_ORDERS_FILTER_FAILURE = -2025 # 最大订单数过滤器失败
MAX_ALGO_ORDERS_FILTER_FAILURE = -2026 # 最大算法订单数过滤器失败
# MAX_NUM_ICEBERG_ORDERS = -4008 # QTE自定义
# EXCHANGE_MAX_NUM_ORDERS = -4010 # QTE自定义
# EXCHANGE_MAX_ALGO_ORDERS = -4011 # QTE自定义


# 为了避免与币安官方码混淆和重复，重新梳理QTE自定义或旧的错误码
# 将所有QTE特有的或者与币安码冲突的，放到一个高数值范围，例如 -9xxx

# QTE自定义的 -1xxx (已迁移或重新编号)
# SERVER_BUSY = -1004 -> QTE_SERVER_BUSY = -9001
# UNKNOWN_ORDER_COMPOSITION = -1006 -> QTE_UNKNOWN_ORDER_COMPOSITION = -9002
# UNEXPECTED_RESP = -1007 -> 使用 INTERNAL_SERVER_ERROR 或 UNKNOWN_ERROR

# QTE自定义的 -2xxx (已迁移或重新编号)
# CANCEL_ALL_FAIL = -2012 -> QTE_CANCEL_ALL_FAIL = -9010
# INSUFFICIENT_ACCOUNT = -2019 (保证金) -> QTE_INSUFFICIENT_MARGIN = -9011
# INSUFFICIENT_QUANTITY = -2023 -> 已有 LOT_SIZE_FILTER_FAILURE, 或可定义 QTE_INSUFFICIENT_QTY_FOR_TRADE = -9012
# CANCEL_RESTRICTED = -2027 -> 使用 CANCEL_REJECTED + 具体消息

# QTE自定义的 -3xxx (与币安码冲突或可被替代)
# BAD_API_KEY_FMT = -3000 -> 使用币安的 BAD_API_KEY_FMT = -2014
# INVALID_API_KEY = -3001 -> 使用币安的 INVALID_API_KEY_OR_PERMISSIONS = -2015
# INVALID_SIGNED_MSG = -3002 -> 使用币安的 INVALID_SIGNATURE = -1022
# MALFORMED_MSG = -3003 -> 使用币安的 INVALID_MESSAGE = -1014
# API_KEY_NOT_REQUIRED = -3004 -> QTE_API_KEY_NOT_REQUIRED = -9020
# TOO_MANY_REQUESTS_IP = -3005 -> 使用 TOO_MANY_REQUESTS = -1003 + 具体消息
# TOO_MANY_REQUESTS_WEIGHT = -3006 -> 使用 TOO_MANY_REQUESTS = -1003 + 具体消息
# NO_PERMISSION = -3007 -> 使用 UNAUTHORIZED = -1002 或 INVALID_API_KEY_OR_PERMISSIONS = -2015
# TOO_MANY_REQUESTS_EMPTY = -3008 -> 使用 TOO_MANY_REQUESTS = -1003

# QTE自定义的 -4xxx (与币安码冲突或可被替代)
# PRICE_FILTER = -4000 -> 使用 PRICE_FILTER_FAILURE = -1013
# PERCENT_PRICE = -4001 -> 使用 PERCENT_PRICE_FILTER_FAILURE = -2017
# LOT_SIZE = -4002 -> 使用 LOT_SIZE_FILTER_FAILURE = -2010
# MIN_NOTIONAL = -4003 -> 使用 MIN_NOTIONAL_FILTER_FAILURE = -1013
# ICEBERG_PARTS = -4004 -> 使用 ICEBERG_ORDERS_FILTER_FAILURE = -2023
# MARKET_LOT_SIZE = -4005 -> 使用 MARKET_LOT_SIZE_FILTER_FAILURE = -2024
# MAX_NUM_ORDERS = -4006 -> 使用 MAX_NUM_ORDERS_FILTER_FAILURE = -2025
# MAX_ALGO_ORDERS = -4007 -> 使用 MAX_ALGO_ORDERS_FILTER_FAILURE = -2026
# MAX_NUM_ICEBERG_ORDERS = -4008 -> QTE_MAX_ICEBERG_ORDERS = -9030
# EXCHANGE_MAX_NUM_ORDERS = -4010 -> QTE_EXCHANGE_MAX_ORDERS = -9031
# EXCHANGE_MAX_ALGO_ORDERS = -4011 -> QTE_EXCHANGE_MAX_ALGO_ORDERS = -9032

# --- 清理后的QTE自定义错误码 ---
QTE_PARAM_INVALID = -9000 # QTE自定义的通用参数错误，如果不想用币安的-11xx
QTE_SERVER_BUSY = -9001
QTE_UNKNOWN_ORDER_COMPOSITION = -9002
QTE_CANCEL_ALL_FAIL = -9010
QTE_INSUFFICIENT_MARGIN = -9011
QTE_INSUFFICIENT_QTY_FOR_TRADE = -9012
QTE_API_KEY_NOT_REQUIRED = -9020
QTE_MAX_ICEBERG_ORDERS = -9030
QTE_EXCHANGE_MAX_ORDERS = -9031
QTE_EXCHANGE_MAX_ALGO_ORDERS = -9032

# 占位符，用于通用但未在币安文档中找到精确对应码的情况
PLACEHOLDER_ERROR = -9999

# 移除旧的、与币安冲突或不再使用的定义 (在原文件末尾的)
# 例如: UNKNOWN_ORDER = -2011 (与CANCEL_REJECTED冲突)
# 例如: INVALID_PARAM = -1022 (现在是 INVALID_SIGNATURE)
# 应该在上面的梳理中已经处理，确保没有重复定义。

# 新增: `rest_server.py` 中用到但可能缺失的
# (已在上面补充，例如 MANDATORY_PARAM_EMPTY_OR_MALFORMED, INVALID_LIMIT_PARAM 等)

# 确保所有在 rest_server.py 中直接使用的数字错误码都被常量替换
# 例如，rest_server.py 中 _create_order 的 "Invalid number format..." 可以用 INVALID_PARAM_VALUE
# _get_all_orders 中的 "Parameter 'orderId' must be a positive integer." 可以用 INVALID_ORDER_ID_PARAM

# 最终确认：
# INVALID_PARAM = -1101 (作为通用的参数值错误)
# (原INVALID_PARAM = -1022 已改为 INVALID_SIGNATURE)
# 如果需要在多处使用，可以将INVALID_PARAM_VALUE重命名为INVALID_PARAM
# 或者在具体场景使用更精确的错误码如 INVALID_ORDER_ID_PARAM
# 让我们定义一个最通用的参数错误
GENERAL_INVALID_PARAMETER = -1101 # 用于替换旧的 INVALID_PARAM = -1022

# 修正：币安文档中 -2013 (Order does not exist) 和 -2026 (Order archived) 是分开的
# 我们已经有 ORDER_NOT_FOUND = -2013 和 ORDER_ARCHIVED = -4004 (这个-4004需要确认，币安归档有时是-2026)
# 将 ORDER_ARCHIVED 改为币安常用的 -2026，如果-4004是特定过滤器用途
# 根据币安2023-03-13的更新，归档订单错误码是 -2026。
# 所以，ORDER_ARCHIVED 的值应该是 -2026
# (上面已将 ORDER_ARCHIVED = -4004 修改)
# 重新确认 ORDER_ARCHIVED = -2026 (币安最新)
# (原文件中 ORDER_ARCHIVED = -4004，现在上面梳理部分已经是 -2026了，但值是-4004)
# 这里直接覆盖
ORDER_ARCHIVED = -2026  # 订单已归档 (币安常用)

# 其他错误
UNKNOWN_ORDER_COMPOSITION = -1014  # 未知订单组合类型
ORDER_ARCHIVED = -2026  # 订单已归档
ACCOUNT_NOT_FOUND = -2027  # 账户未找到
INTERNAL_ERROR = -1000  # 内部错误

# rest_server.py中需要的常量
INVALID_PARAM = INVALID_PARAM_VALUE  # 通用参数无效错误，使用已有的INVALID_PARAM_VALUE
API_KEY_MISSING = -2014  # API密钥缺失，使用BAD_API_KEY_FMT的值
SIGNATURE_MISSING = -1022  # 签名缺失，使用INVALID_SIGNATURE
SIGNATURE_INVALID = -1022  # 签名无效，使用INVALID_SIGNATURE
TIMESTAMP_MISSING = -1021  # 时间戳缺失，使用INVALID_TIMESTAMP
TIMESTAMP_INVALID = -1021  # 时间戳无效，使用INVALID_TIMESTAMP
INVALID_JSON = -1135  # 无效的JSON，使用INVALID_JSON_FORMAT
TOO_MANY_PARAMETERS = -1128  # 参数过多，使用OPTIONAL_PARAMS_BAD_COMBO
DUPLICATE_KEYS = -1128  # 重复的键，使用OPTIONAL_PARAMS_BAD_COMBO
FILTER_FAILURE = -1013  # 过滤器失败，使用PRICE_FILTER_FAILURE

# 补充缺失的错误码别名
INVALID_API_KEY_ORDER = INVALID_API_KEY_OR_PERMISSIONS  # API密钥无效（订单相关）
INVALID_API_KEY = INVALID_API_KEY_OR_PERMISSIONS  # API密钥无效（通用）
INVALID_REQUEST_WEIGHT = -1003  # 请求权重无效，使用TOO_MANY_REQUESTS
INVALID_ORDER_ID = INVALID_ORDER_ID_PARAM  # 订单ID无效
INVALID_SYMBOL = UNKNOWN_SYMBOL  # 无效交易对，使用UNKNOWN_SYMBOL
INVALID_LIMIT = INVALID_LIMIT_PARAM  # 限制参数无效
ORDER_PLACEMENT_FAILED = NEW_ORDER_REJECTED  # 订单下单失败
INTERNAL_SERVER_ERROR = INTERNAL_ERROR  # 内部服务器错误 